version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: numbers
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d numbers"]
      interval: 3s
      timeout: 3s
      retries: 5

  # migrator:
  #   build: .
  #   command: ["/bin/migrator"]
  #   volumes:
  #     - ./migrations:/app/migrations
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  app:
    build: .
    command: ["/bin/app"]
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

